version: '3.8'
services:
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: mmouser
      POSTGRES_PASSWORD: mmopass
      POSTGRES_DB: mmodb
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
